SELECT [Item No]
    ,TRIM([Vendor Reference]) AS [Vendor Reference]
    ,TRIM([D2C Master SKU]) AS [D2C Master SKU]
    ,[Brand Code]
    ,[Description]
    ,[Description 2]
    ,TRIM([Colours]) AS [Colours]
    ,TRIM([Size 1]) AS [Size 1]
    ,[Size 1 Unit]
    ,[UOM]
    ,[Season]
    ,[Item Info]
    ,[Category Code] AS [Category]
    ,[Group Code] AS [Group]
FROM [dItem]
WHERE [Brand Code] IN ('SCA', 'INA', 'ABA');
